name: Build and Deploy to GCP VM

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy: # This is the job ID (can be any name)
    runs-on: ubuntu-latest # This is required
    steps:
      - name: Deploy to GCP VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_VM_USER }}
          key: ${{ secrets.GCP_VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.GCP_VM_USER }}/mcp-app/mcp-nba
            docker compose down
            git pull origin main
            docker compose up -d
